source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'wdm', '>= 0.1.0'
  gem 'jekyll', '3.9.0'  # Mantener esta versión
  gem 'github-pages', '212'  # Especifica la versión
  gem 'fiddle', '1.1.4'  # Especifica la versión
  gem 'classifier-reborn', '2.3.0'
  gem 'jekyll-archives', '2.2.1'
  gem 'jekyll-email-protect', '1.1.0'
  gem 'jekyll-feed', '0.15.1'
  gem 'jekyll-get-json', '1.0.0'
  gem 'jekyll-imagemagick', '1.4.0'
  gem 'jekyll-jupyter-notebook', '0.0.6'
  gem 'jekyll-link-attributes', '1.0.1'
  gem 'jekyll-minifier', '0.1.10'
  gem 'jekyll-paginate-v2', '3.0.0'
  gem 'jekyll-regex-replace', '1.1.0'
  gem 'jekyll-scholar', '5.16.0'  # Cambia a una versión anterior
  gem 'jekyll-sitemap'
  gem 'jekyll-tabs', '1.2.1'
  gem 'jekyll-toc', '0.19.0'
  gem 'jekyll-twitter-plugin', '2.1.0'
  gem 'jemoji', '0.12.0'
  gem 'unicode_utils', '1.4.0'
  gem 'webrick', '1.8.2'  # Especifica la versión
end

group :other_plugins do
  gem 'css_parser', '1.19.1'
  gem 'feedjira', '3.2.3'
  gem 'httparty', '0.22.0'
  gem 'i18n', '0.9.5'
  gem 'kramdown', '2.3.0'
  gem 'liquid', '4.0.3'
  gem 'rouge', '3.26.0'
  gem 'github-pages-health-check', '1.17.0'
  gem 'jekyll-avatar', '0.7.0'
  gem 'jekyll-coffeescript', '1.1.1'
  gem 'jekyll-commonmark-ghpages', '0.1.6'
  gem 'jekyll-default-layout', '0.1.4'
  gem 'jekyll-github-metadata', '2.13.0'
  gem 'jekyll-remote-theme', '0.4.2'
  gem 'jekyll-seo-tag', '2.7.1'
  gem 'jekyll-theme-architect', '0.1.1'
  gem 'jekyll-theme-cayman', '0.1.1'
  gem 'jekyll-theme-dinky', '0.1.1'
  gem 'jekyll-theme-hacker', '0.1.2'
  gem 'jekyll-theme-leap-day', '0.1.1'
  gem 'jekyll-theme-merlot', '0.1.1'
  gem 'jekyll-theme-midnight', '0.1.1'
  gem 'jekyll-theme-minimal', '0.1.1'
  gem 'jekyll-theme-modernist', '0.1.1'
  gem 'jekyll-theme-primer', '0.5.4'
  gem 'jekyll-theme-slate', '0.1.1'
  gem 'jekyll-theme-tactile', '0.1.1'
  gem 'jekyll-theme-time-machine', '0.1.1'
  gem 'fast-stemmer', '1.0.2'
  gem 'deep_merge', '1.2.2'
  gem 'cssminify2', '2.0.1'
  gem 'htmlcompressor', '0.4.0'
  gem 'json-minify', '0.0.3'
  gem 'uglifier', '4.2.1'
  gem 'bibtex-ruby', '4.4.7'
  gem 'citeproc-ruby', '1.1.14'
  gem 'csl-styles', '1.0.1.11'
  gem 'gemoji', '3.0.1'
  gem 'loofah', '2.22.0'
  gem 'sax-machine', '1.3.2'
  gem 'mini_mime', '1.1.5'
  gem 'multi_xml', '0.7.1'
  gem 'public_suffix', '4.0.7'
  gem 'concurrent-ruby', '1.3.4'
  gem 'rexml', '3.3.9'
  gem 'coffee-script-source', '1.11.1'
  gem 'commonmarker', '0.17.13'
  gem 'jekyll-commonmark', '1.3.1'
  gem 'json', '2.7.2'
  gem 'latex-decode', '0.4.0'
  gem 'citeproc', '1.0.10'
  gem 'csl', '1.6.0'
  gem 'activesupport', '3.2.22.5'
  gem 'crass', '1.0.6'
  gem 'faraday', '2.12.0'
  gem 'ruby-enum', '0.9.0'
  gem 'namae', '1.2.0'
  gem 'multi_json', '1.15.0'
  gem 'faraday-net_http', '3.3.0'
  gem 'logger', '1.6.1'
  gem 'uri', '0.13.1'
end
